// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/glass-buttons/CurrentGlass.tsx": () => import("../components/mockups/glass-buttons/CurrentGlass.tsx"),
  "./components/mockups/glass-buttons/PurpleGlass.tsx": () => import("../components/mockups/glass-buttons/PurpleGlass.tsx")
};
